### PR TITLE
Fixes for 1.0. All tests pass

### PR DESCRIPTION
**Pull request by rejuvyesh**
`contains` is now `occursin`. Not sure whether we should change the API.

### CODE REVIEW

**Comment by tawheeler** [comment]
Any idea why Travis is failing?

**Comment by rejuvyesh** [comment]
Need to fix `.travis.yml`.

**Comment by rejuvyesh** [comment]
Now `contains` is the issue. Works on 1.0 but not on 0.7.

**Comment by tawheeler** [comment]
Please make a PR for the 0.7 fixes and then make a separate PR for the 1.0 fixes in which the required version number is bumped.

**Pull request merged**
